# Generated by Django 3.0.5 on 2020-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
